### ISSUE TITLE
Item Code Not Found: blade-blackguard;blade-forlorn;blade-admin.

### ISSUE THREAD

**Issue by Diometus** [kenigvovan/canjewelry_7#1]
Having the below 'spam' on the following server version: 1.18.10, 1.18.12, 1.18.13

1. [Server Debug] [canjewelry] Item with "*blade-blackguard" code not found
2. [Server Debug] [canjewelry] Item with "*blade-forlorn" code not found
3. [Server Debug] [canjewelry] Item with "*blade-admin" code not found

I think the solution would be to change the item codes to the updated item codes:

*blade-admin   ->  blade-longsword-admin
*blade-forlorn   ->  blade-forlorn-iron
*blade-blackguard   ->   blade-blackguard-iron

Now if it isn't these items you are referring to... I don't know. But I do see the 'spam' in my server log & debug thus figured I should report it to you.

**Comment by kenigvovan** [comment]
Hi, thanks for info, updated it in 0.1.18
