### ISSUE TITLE
New Gem Idea: Heliodor, a Knife-equipable gem for Looting Corpses

### ISSUE THREAD

**Issue by UmbralSurvivor** [kenigvovan/canjewelry_7#2]
Helidor would be yellow colored, and found in Granite and Limestone. It would grant an increase in loot from harvested corpses, and as such would only be applicable for Knives.
Alternatively, Garnet could be the gem of choice. It would be found in the same places Heliodor would have been, but be a dark red instead of yellow.

[Wikipedia](https://en.wikipedia.org/wiki/Beryl#Golden_beryl_and_heliodor)
Reason for Heliodor, specifically: In a book series I like ([The Stormlight Archive](https://en.wikipedia.org/wiki/The_Stormlight_Archive)), Heliodor can be used to [transmute](https://coppermind.net/wiki/Soulcasting) things into meat. Garnet does the same, but for Blood. Eight other gems could transmute into other things as well, together known as the [Ten Essences](https://coppermind.net/wiki/Ten_Essences).

**Comment by kenigvovan** [comment]
I'll take a look at it when I'll return to the mod next time

**Comment by kenigvovan** [comment]
Citrine now has animal loot drop rate buff
