### ISSUE TITLE
Crash when panning

### ISSUE THREAD

**Issue by Mad-Gnome** [kenigvovan/canjewelry_7#3]
VS: 1.19.5
CAN Jewelry: 0.2.22

When I try to pan ore I immediately experience a client crash.  I am playing on a MP server.  Two other players have experienced the same crash.

[client-crash.txt](https://github.com/kenigvovan/canjewelry_7/files/14767041/client-crash.txt)

**Comment by kenigvovan** [comment]
What ore do you use? Any exceptions in debug/main log?

**Comment by Mad-Gnome** [comment]
0.2.23 Fixed the issues, but players connecting to a MP server have to delete their old CAN Jewelry Modconfig as well.
